apiVersion: v1
kind: Service
metadata:
  name: oci-registry
  namespace: default
spec:
  selector:
    app: oci-registry
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-registry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oci-registry
  template:
    metadata:
      labels:
        app: oci-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        volumeMounts:
        - name: tls-certs
          mountPath: /certs
          readOnly: true
        - name: registry-storage
          mountPath: /var/lib/registry
      volumes:
      - name: tls-certs
        secret:
          secretName: oci-registry-tls
      - name: registry-storage
        emptyDir: {}